name: regenerate

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      proto_ref:
        description: 'The ref of the proto repo that triggered the dispatch.'
        required: true
      proto_sha:
        description: 'The sha of the proto repo that triggered the dispatch.'
        required: false
      openapi_grpc_sha:
        description: 'The sha of the openapi-grpc repo that triggered the dispatch'
        required: true

env:
  VAULT_ADDR: https://vault.eng.aserto.com/
  VAULT_TOKEN:  ${{ secrets.VAULT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read Configuration
        uses: hashicorp/vault-action@v2.1.0
        id: vault
        with:
          url: ${{ env.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/github    "READ_WRITE_TOKEN"    | READ_WRITE_TOKEN;
            kv/data/github    "SSH_PRIVATE_KEY"     | SSH_PRIVATE_KEY;
            kv/data/github    "USERNAME"            | USERNAME;

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Environment
        run: |
            mkdir -p $HOME/.ssh
            umask 0077 && echo -e "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
            ssh-keyscan github.com >> $HOME/.ssh/known_hosts
            
            git config --global url."git@github.com:".insteadOf https://github.com/
            git config --global user.email "github-bot@aserto.com"
            git config --global user.name "Aserto Bot"

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile

      - name: Generate commit_hash.sh
        run: echo $'COMMIT_HASH=${COMMIT_HASH}\n' >> downloaded/commit_hash.sh
        shell: bash
        env:
          COMMIT_HASH: ${{ github.event.inputs.openapi_grpc_sha }}

      - name: Generate
        run: ./generate.sh

      - name: Create Pull Request
        if: github.event_name == 'workflow_dispatch'
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.vault.outputs.READ_WRITE_TOKEN }}
          commit-message: Regenerate Type Definitions for Proto ${{ github.events.inputs.proto_ref }}
          signoff: false
          branch: proto/${{ github.events.inputs.proto_ref }}
          delete-branch: true
          title: 'Auto-Regenerate: ${{ github.events.inputs.proto_ref }}'
          body: |
            Auto-generated PR to create Console Type Definitions for ${{ github.events.inputs.proto_ref }}
            - Upon approval, tag the resulting commit with the version from this ref
          draft: false
